modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "hunger_tweaks"
version = "${version}"
displayName = "Hunger Tweaks"
authors = "Daedelus"
description = '''
Changes exhaust and regeneration intensity.
'''
logoFile = "icon.png"

[[dependencies.hunger_tweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hunger_tweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "hunger_tweaks.mixins.json"
